---
Name: rutas
After: framework/routes#coreroutes
---
Director:
  rules:
    # '': 'HomePage_Controller'
    'noticias/detalle-noticia': 'NoticiaDetalleController',    
    'concursos/detalle-concurso': 'ConcursoDetalleController',    
    'documentos': 'DocumentoController',
    'biblioteca/$ID': 'BibliotecaPageController' ,
    'bibliotecas/detalle-biblioteca': 'BibliotecaDetalleController' 
